package com.abbos.financetrackerbot.state;

/**
 * @author Aliabbos Ashurov
 * @since 09/January/2025  14:02
 **/
public class UserBaseMenuState implements State {
    public static final String USER_ON_BASE_MENU = "USER_ON_BASE_MENU";
    public static final String USER_BASE_MENU_STATE_REPORTS = "USER_BASE_MENU_STATE_REPORTS";
    public static final String USER_BASE_MENU_STATE_SETTINGS = "USER_BASE_MENU_STATE_SETTINGS";

    public static final String USER_MENU_REPORTS_STATE_MONTHLY_INCOME = "USER_MENU_REPORTS_STATE_MONTHLY_INCOME";
    public static final String USER_MENU_REPORTS_STATE_MONTHLY_EXPENSES = "USER_MENU_REPORTS_STATE_MONTHLY_EXPENSES";
    public static final String USER_MENU_REPORTS_STATE_ADDITIONAL_REPORTS = "USER_MENU_REPORTS_STATE_ADDITIONAL_REPORTS";

    public static final String USER_MENU_SETTINGS_CHANGE_PROFILE_INFORMATION = "USER_MENU_SETTINGS_CHANGE_PROFILE_INFORMATION";
    public static final String USER_MENU_SETTINGS_CHANGE_VIEW_CURRENT_ACCESS_RIGHTS = "USER_MENU_SETTINGS_CHANGE_VIEW_CURRENT_ACCESS_RIGHTS";
    public static final String USER_MENU_SETTINGS_CHANGE_PASSWORD = "USER_MENU_SETTINGS_CHANGE_PASSWORD";
    public static final String USER_MENU_SETTINGS_CHANGE_LANGUAGE = "USER_MENU_SETTINGS_CHANGE_LANGUAGE";
}
